# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = NetworkServer
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"../../../../../libcpp/cryptopp-8-7-0/lib/x64-debug" \
    -L"../../../../../libcpp/mysql-connector-8-0-32-debug/lib64/vs14/debug" \
    -lmysqlcppconn8-static \
    -lmysqlcppconn-static \
    -lcryptlib
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(NetworkServer.pri)
