# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = NetworkClient
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"../../../../../libcpp/cryptopp-8-7-0/lib/x64-debug" \
    -lcryptlib
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(NetworkClient.pri)
